var simplemaps_usmap_mapdata = {
  main_settings: {
    //General settings
    width: '1002',
    background_color: '#FFFFFF',
    background_transparent: 'yes',
    popups: 'on_click', // or 'detect', 'on_hover', 'on_click', 'off'
    //  popup_nocss: 'yes',

    //State defaults
    state_description: '',
    state_color: '#43CA9E',
    state_hover_color: '#56de9e',
    state_url: '',
    border_size: 3,
    border_color: '#82e3c9',
    all_states_inactive: 'yes',
    all_states_zoomable: 'no',

    //Location defaults
    location_description:
      '<b>Lorem Ipsum</b> is simply dummy text<br> of the printing and typesetting <br>industry. ',
    location_color: 'orange',
    location_pulse: 'yes',
    location_pulse_size: '3',
    location_opacity: 0.9,
    location_hover_opacity: 1,
    location_url: '',
    location_size: 24,
    location_type: 'circle',
    location_border_color: '#42ca9e',
    location_border: 3,
    location_hover_border: 2.5,
    all_locations_inactive: 'no',
    all_locations_hidden: 'no',

    //Label defaults
    label_color: '#000000',
    label_hover_color: '#ffffff',
    label_size: 15,
    label_font: 'Calibri',
    hide_labels: 'no',

    //Zoom settings
    manual_zoom: 'no',
    back_image: 'no',
    arrow_box: 'no',
    navigation_size: '40',
    navigation_color: '#f7f7f7',
    navigation_border_color: '#636363',
    initial_back: 'no',
    initial_zoom: -1,
    initial_zoom_solo: 'no',
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: 'yes',
    zoom_percentage: 0.99,
    zoom_time: 0.5,

    //Popup settings
    popup_color: 'white',
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: '15px/1.5 calibri, Arial, Helvetica, sans-serif',
    popup_nocss: 'no',

    //Advanced settings
    div: 'map',
    auto_load: 'yes',
    rotate: '0',
    url_new_tab: 'yes',
    images_directory: 'default',
    import_labels: 'no',
    fade_time: 0.1,
    link_text: 'View Website',
  },
  state_specific: {
    HI: {
      name: 'Hawaii',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    AK: {
      name: 'Alaska',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    FL: {
      name: 'Florida',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    NH: {
      name: 'New Hampshire',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    VT: {
      name: 'Vermont',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    ME: {
      name: 'Maine',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    RI: {
      name: 'Rhode Island',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    NY: {
      name: 'New York',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    PA: {
      name: 'Pennsylvania',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    NJ: {
      name: 'New Jersey',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    DE: {
      name: 'Delaware',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    MD: {
      name: 'Maryland',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    VA: {
      name: 'Virginia',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    WV: {
      name: 'West Virginia',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    OH: {
      name: 'Ohio',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    IN: {
      name: 'Indiana',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    IL: {
      name: 'Illinois',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    CT: {
      name: 'Connecticut',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    WI: {
      name: 'Wisconsin',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    NC: {
      name: 'North Carolina',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    DC: {
      name: 'District of Columbia',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    MA: {
      name: 'Massachusetts',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    TN: {
      name: 'Tennessee',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    AR: {
      name: 'Arkansas',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    MO: {
      name: 'Missouri',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    GA: {
      name: 'Georgia',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    SC: {
      name: 'South Carolina',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    KY: {
      name: 'Kentucky',
      description: 'default',
      color: 'default',
      zoomable: 'no',
      hover_color: 'default',
      url: 'default',
    },
    AL: {
      name: 'Alabama',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    LA: {
      name: 'Louisiana',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    MS: {
      name: 'Mississippi',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    IA: {
      name: 'Iowa',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    MN: {
      name: 'Minnesota',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    OK: {
      name: 'Oklahoma',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    TX: {
      name: 'Texas',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    NM: {
      name: 'New Mexico',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    KS: {
      name: 'Kansas',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    NE: {
      name: 'Nebraska',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    SD: {
      name: 'South Dakota',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    ND: {
      name: 'North Dakota',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    WY: {
      name: 'Wyoming',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    MT: {
      name: 'Montana',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    CO: {
      name: 'Colorado',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    UT: {
      name: 'Utah',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    AZ: {
      name: 'Arizona',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    NV: {
      name: 'Nevada',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    OR: {
      name: 'Oregon',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    WA: {
      name: 'Washington',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    CA: {
      name: 'California',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    MI: {
      name: 'Michigan',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    ID: {
      name: 'Idaho',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
    },
    GU: {
      name: 'Guam',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
      hide: 'yes',
    },
    VI: {
      name: 'Virgin Islands',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
      hide: 'yes',
    },
    PR: {
      name: 'Puerto Rico',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
      hide: 'yes',
    },
    AS: {
      name: 'American Samoa',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
      hide: 'yes',
    },
    MP: {
      name: 'Northern Mariana Islands',
      description: 'default',
      color: 'default',
      hover_color: 'default',
      url: 'default',
      hide: 'yes',
    },
  },
  locations: {
    0: {
      name: 'March 17, 2021',
      description: `<h3>Los Angles, CA</h3>
        <div>
          <div class="place-topics">Canvas For Elementary</div>
          <a class="red-button" href="https://events.bizzabo.com/292529">
            REGISTER NOW
          </a>
        </div>
        `,
      lat: '34.0522',
      lng: '-118.2437',
      color: 'default',
    },
    1: {
      name: 'March 17, 2021',
      description: `<h3>California</h3>
        <div>
          <div class="place-topics">Build an Equitable Foundation for Learning</div>
          <a class="red-button" href="https://events.bizzabo.com/291342">
            REGISTER NOW
          </a>
        </div>
        `,
      lat: '40.199879',
      lng: '-122.201111',
      color: 'default',
    },
    2: {
      name: 'March 23, 2021',
      description: `<h3>Las Vegas, NV</h3>
        <div class="place-topics">Canvas For Elementary</div>
        <div>
          <a class="red-button" href="https://events.bizzabo.com/292532">
            REGISTER NOW
          </a>
        </div>`,
      lat: '36.1699',
      lng: '-115.1398',
    },
    3: {
      name: 'March 24, 2021',
      description: `<h3>Texas</h3>
        <div class="place-topics">Enable student centered learning with Tech</div>
        <div>
          <a class="red-button" href="https://events.bizzabo.com/292534">
            REGISTER NOW
          </a>
        </div>`,
      lat: '30.221102',
      lng: '-97.619215',
    },
    4: {
      name: 'April 8, 2021',
      description: `<h3>Chicago, IL</h3>
        <div class="place-topics">Enhance Student & Teacher Success</div>
        <div>
          <a class="red-button" href="https://events.bizzabo.com/292535">
            REGISTER NOW
          </a>
        </div>`,
      lat: '41.881832',
      lng: '-87.623177',
    },
    5: {
      name: 'April 20, 2021',
      description: `<h3>New York City, NY</h3>
        <div class="place-topics">Close the Gap in Distance Learning</div>
        <div>
          <a class="red-button" href="https://events.bizzabo.com/292536">
            REGISTER NOW
          </a>
        </div>`,
      lat: '41.730610',
      lng: '-73.935242',
    },
    6: {
      name: 'March 11, 2021',
      description: `<h3>Washington DC Metro, DC</h3>
        <div class="place-topics">Mastery Connect for Elementary</div>
        <div>
          <a class="red-button" href="https://events.bizzabo.com/292537">
            REGISTER NOW
          </a>
        </div>`,
      lat: '39.1290',
      lng: '-77.3784',
    },
    7: {
      name: 'April 13, 2021',
      description: `<h3>Atlanta, GA</h3>
        <div class="place-topics">Leverage Data to Drive Student Success</div>
        <div>
          <a class="red-button" href="https://events.bizzabo.com/292539">
            REGISTER NOW
          </a>
        </div>`,
      lat: '33.7490',
      lng: '-84.3880',
    },
    8: {
      name: 'April 6, 2021',
      description: `<h3>Tampa, FL</h3>
        <div class="place-topics">Canvas & Mastery Connect</div>
        <div>
          <a class="red-button" href="https://events.bizzabo.com/292540">
            REGISTER NOW
          </a>
        </div>`,
      lat: '27.9506',
      lng: '-82.4572',
    },

    // 11: {
    //   name: 'CA Marker',
    //   description: 'default',
    //   lat: '38.1378',
    //   lng: '-119.7871',
    //   inactive: 'yes',
    //   type: 'image',
    //   image_url: 'https://i.ibb.co/kHQMjhB/map-red-pin.png',
    //   size: '45',
    // },
    // 12: {
    //   name: 'NV Marker',
    //   description: 'default',
    //   lat: '40.876019',
    //   lng: '-117.224121',
    //   inactive: 'yes',
    //   type: 'image',
    //   image_url: 'https://i.ibb.co/kHQMjhB/map-red-pin.png',
    //   size: '45',
    // },
    // 13: {
    //   name: 'TX Marker',
    //   description: 'default',
    //   lat: '33.4896998',
    //   lng: '-95.8592625',
    //   inactive: 'yes',
    //   type: 'image',
    //   image_url: 'https://i.ibb.co/kHQMjhB/map-red-pin.png',
    //   size: '45',
    // },
    // 14: {
    //   name: 'IL Marker',
    //   description: 'default',
    //   lat: '42.733061',
    //   lng: '-88.446194',
    //   inactive: 'yes',
    //   type: 'image',
    //   image_url: 'https://i.ibb.co/kHQMjhB/map-red-pin.png',
    //   size: '45',
    // },
    // 15: {
    //   name: 'NY Marker',
    //   description: 'default',
    //   lat: '42.979275',
    //   lng: '-73.695792',
    //   inactive: 'yes',
    //   type: 'image',
    //   image_url: 'https://i.ibb.co/kHQMjhB/map-red-pin.png',
    //   size: '45',
    // },
    // 16: {
    //   name: 'DC Marker',
    //   description: 'default',
    //   lat: '40.279526',
    //   lng: '-77.024268',
    //   inactive: 'yes',
    //   type: 'image',
    //   image_url: 'https://i.ibb.co/kHQMjhB/map-red-pin.png',
    //   size: '45',
    // },
    // 17: {
    //   name: 'GA Marker',
    //   description: 'default',
    //   lat: '34.987428',
    //   lng: '-84.145982',
    //   inactive: 'yes',
    //   type: 'image',
    //   image_url: 'https://i.ibb.co/kHQMjhB/map-red-pin.png',
    //   size: '45',
    // },
    // 18: {
    //   name: 'FL Marker',
    //   description: 'default',
    //   lat: '28.994402',
    //   lng: '-81.360254',
    //   inactive: 'yes',
    //   type: 'image',
    //   image_url: 'https://i.ibb.co/kHQMjhB/map-red-pin.png',
    //   size: '45',
    // },
    19: {
      name: '',
      description: '',
      lat: '31.0140674',
      lng: '-103.2605111',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/dfLnbwQ/tx-boots-icon-2x.png',
      size: '54',
    },
    20: {
      name: '',
      description: '',
      lat: '34.0140674',
      lng: '-101.8605111',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/2g5qLZ2/tx-cowboyhut-icon-2x.png',
      size: '36',
    },
    21: {
      name: '',
      description: '',
      lat: '39.000000',
      lng: '-89.000000',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/mh4GrkS/il-chicagomelenium-icon-2x.png',
      size: '21',
    },
    22: {
      name: '',
      description: '',
      lat: '44.000000',
      lng: '-77.500000',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/1QR9tzK/nyc-torch-icon-2x.png',
      size: '63',
    },
    23: {
      name: '',
      description: '',
      lat: '32.247875',
      lng: '-82.141162',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/855z9KG/ga-pears-icon-2x.png',
      size: '30',
    },
    24: {
      name: '',
      description: '',
      lat: '27.454402',
      lng: '-79.760254',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/FDx349h/fl-orange-icon-2x.png',
      size: '36',
    },
    27: {
      name: '',
      description: '',
      lat: '35.096456',
      lng: '-120.394026',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/8D28K09/ca-bear-icon-2x.png',
      size: '25',
    },
    28: {
      name: '',
      description: '',
      lat: '33.896456',
      lng: '-116.094026',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/QPDsmns/ca-hollywood-icon-2x.png',
      size: '15',
    },
    29: {
      name: '',
      description: '',
      lat: '37.439974',
      lng: '-115.274909',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/CbnBdrX/nv-vegas-icon-2x.png',
      size: '35',
    },
    30: {
      name: '',
      description: '',
      lat: '40.008536',
      lng: '-77.761051',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/qsW07gP/wdc-monument-icon-2x.png',
      size: '35',
    },
    98: {
      name: '',
      description: '',
      lat: '34.0522',
      lng: '-118.2437',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/DK8KfBc/schoolbus-flat-xs-2x.png',
      size: '42',
    },
    99: {
      name: '',
      description: '',
      lat: '34.0522',
      lng: '-118.2437',
      type: 'image',
      inactive: 'yes',
      image_url: 'https://i.ibb.co/HgHh67q/winnebago-flat-xs-2x.png',
      size: '42',
    },
  },
  lines: {
    1: {
      name: 'Fresno to LA',
      origin_location: '0',
      destination_location: '1',
      color: '#2b6081',
      angle: -15,
      size: 3,
      dash: '-',
    },
    2: {
      name: 'LA to Las Vegas',
      origin_location: '1',
      destination_location: '2',
      color: '#2b6081',
      angle: -10,
      size: 3,
      dash: '-',
    },
    3: {
      name: 'Las Vegas to Houston',
      origin_location: '2',
      destination_location: '3',
      color: '#2b6081',
      angle: -20,
      size: 3,
      dash: '-',
    },
    4: {
      name: 'Houston to DFW',
      origin_location: '3',
      destination_location: '4',
      color: '#2b6081',
      angle: -30,
      size: 3,
      dash: '-',
    },
    5: {
      name: 'DFW to Chicago',
      origin_location: '4',
      destination_location: '5',
      color: '#2b6081',
      angle: -30,
      size: 3,
      dash: '-',
    },
    6: {
      name: 'Chicago to NYC',
      origin_location: '5',
      destination_location: '6',
      color: '#2b6081',
      angle: -25,
      size: 3,
      dash: '-',
    },
    7: {
      name: 'NYC to DC',
      origin_location: '6',
      destination_location: '7',
      color: '#2b6081',
      angle: 20,
      size: 3,
      dash: '-',
    },
    8: {
      name: 'NYC to DC',
      origin_location: '7',
      destination_location: '8',
      color: '#2b6081',
      angle: 20,
      size: 3,
      dash: '-',
    }
  },
  labels: {
    NH: {
      // parent_id: "NH",
      x: '932',
      y: '183',
      // pill: "yes",
      width: 45,
      display: 'all',
    },
    VT: {
      //parent_id: "VT",
      x: '883',
      y: '243',
      // pill: "yes",
      width: 45,
      display: 'all',
    },
    RI: {
      // parent_id: "RI",
      x: '932',
      y: '273',
      // pill: "yes",
      width: 45,
      display: 'all',
    },
    NJ: {
      // parent_id: "NJ",
      x: '883',
      y: '273',
      // pill: "yes",
      width: 45,
      display: 'all',
    },
    DE: {
      //  parent_id: "DE",
      x: '883',
      y: '303',
      //  pill: "yes",
      width: 45,
      display: 'all',
    },
    MD: {
      // parent_id: "MD",
      x: '932',
      y: '303',
      // pill: "yes",
      width: 45,
      display: 'all',
    },
    DC: {
      // parent_id: "DC",
      x: '884',
      y: '332',
      //  pill: "yes",
      width: 45,
      display: 'all',
    },
    MA: {
      //  parent_id: "MA",
      x: '932',
      y: '213',
      //  pill: "yes",
      width: 45,
      display: 'all',
    },
    CT: {
      //  parent_id: "CT",
      x: '932',
      y: '243',
      //  pill: "yes",
      width: 45,
      display: 'all',
    },
    HI: {
      parent_id: 'HI',
      x: 305,
      y: 565,
      hover_color: '#000',
      //pill: "yes"
    },
    AK: {
      parent_id: 'AK',
      x: '113',
      y: '495',
    },
    FL: {
      parent_id: 'FL',
      x: '773',
      y: '510',
    },
    ME: {
      parent_id: 'ME',
      x: '893',
      y: '85',
    },
    NY: {
      parent_id: 'NY',
      x: '815',
      y: '158',
    },
    PA: {
      parent_id: 'PA',
      x: '786',
      y: '210',
    },
    VA: {
      parent_id: 'VA',
      x: '790',
      y: '282',
    },
    WV: {
      parent_id: 'WV',
      x: '744',
      y: '270',
    },
    OH: {
      parent_id: 'OH',
      x: '700',
      y: '240',
    },
    IN: {
      parent_id: 'IN',
      x: '650',
      y: '250',
    },
    IL: {
      parent_id: 'IL',
      x: '600',
      y: '250',
    },
    WI: {
      parent_id: 'WI',
      x: '575',
      y: '155',
    },
    NC: {
      parent_id: 'NC',
      x: '784',
      y: '326',
    },
    TN: {
      parent_id: 'TN',
      x: '655',
      y: '340',
    },
    AR: {
      parent_id: 'AR',
      x: '548',
      y: '368',
    },
    MO: {
      parent_id: 'MO',
      x: '548',
      y: '293',
    },
    GA: {
      parent_id: 'GA',
      x: '718',
      y: '405',
    },
    SC: {
      parent_id: 'SC',
      x: '760',
      y: '371',
    },
    KY: {
      parent_id: 'KY',
      x: '680',
      y: '300',
    },
    AL: {
      parent_id: 'AL',
      x: '655',
      y: '405',
    },
    LA: {
      parent_id: 'LA',
      x: '550',
      y: '435',
    },
    MS: {
      parent_id: 'MS',
      x: '600',
      y: '405',
    },
    IA: {
      parent_id: 'IA',
      x: '525',
      y: '210',
    },
    MN: {
      parent_id: 'MN',
      x: '506',
      y: '124',
    },
    OK: {
      parent_id: 'OK',
      x: '460',
      y: '360',
    },
    TX: {
      parent_id: 'TX',
      x: '425',
      y: '435',
    },
    NM: {
      parent_id: 'NM',
      x: '305',
      y: '365',
    },
    KS: {
      parent_id: 'KS',
      x: '445',
      y: '290',
    },
    NE: {
      parent_id: 'NE',
      x: '420',
      y: '225',
    },
    SD: {
      parent_id: 'SD',
      x: '413',
      y: '160',
    },
    ND: {
      parent_id: 'ND',
      x: '416',
      y: '96',
    },
    WY: {
      parent_id: 'WY',
      x: '300',
      y: '180',
    },
    MT: {
      parent_id: 'MT',
      x: '280',
      y: '95',
    },
    CO: {
      parent_id: 'CO',
      x: '320',
      y: '275',
    },
    UT: {
      parent_id: 'UT',
      x: '223',
      y: '260',
    },
    AZ: {
      parent_id: 'AZ',
      x: '205',
      y: '360',
    },
    NV: {
      parent_id: 'NV',
      x: '140',
      y: '235',
    },
    OR: {
      parent_id: 'OR',
      x: '100',
      y: '120',
    },
    WA: {
      parent_id: 'WA',
      x: '130',
      y: '55',
    },
    ID: {
      parent_id: 'ID',
      x: '200',
      y: '150',
    },
    CA: {
      parent_id: 'CA',
      x: '79',
      y: '285',
    },
    MI: {
      parent_id: 'MI',
      x: '663',
      y: '185',
    },
    PR: {
      parent_id: 'PR',
      x: '620',
      y: '545',
    },
    GU: {
      parent_id: 'GU',
      x: '550',
      y: '540',
    },
    VI: {
      parent_id: 'VI',
      x: '680',
      y: '519',
    },
    MP: {
      parent_id: 'MP',
      x: '570',
      y: '575',
    },
    AS: {
      parent_id: 'AS',
      x: '665',
      y: '580',
    },
  },
};
